export const GET_WATCHLIST_REQUEST='GET_WATCHLIST_REQUEST';
export const GET_WATCHLIST_SUCCESS='GET_WATCHLIST_SUCCESS';
export const GET_WATCHLIST_FAIL='GET_WATCHLIST_FAIL';


export const ADD_TO_WATCHLIST_REQUEST="ADD_TO_WATCHLIST_REQUEST";
export const ADD_TO_WATCHLIST_SUCCESS="ADD_TO_WATCHLIST_SUCCESS";
export const ADD_TO_WATCHLIST_FAIL="ADD_TO_WATCHLIST_FAIL";


export const DEL_FROM_WATCHLIST_REQUEST="DEL_FROM_WATCHLIST_REQUEST";
export const DEL_FROM_WATCHLIST_SUCCESS="DEL_FROM_WATCHLIST_SUCCESS";
export const DEL_FROM_WATCHLIST_FAIL="DEL_FROM_WATCHLIST_FAIL";